### ISSUE TITLE
restructure code

### ISSUE THREAD

**Issue by incredibleLeitman** [pothigai/HangManApp#5]
![image](https://github.com/pothigai/HangManApp/assets/24638443/499a1dec-0a1a-4b29-b03c-6c75c0138e92)
When writing code try to combine blocks that achieve the same thing, this will help you and other developers very much to quickly read and understand what the program does.

So here the declaration of the variable "gameState" and the filling of its values basically achieve the same goal and should be grouped together. 
Then, your program should first initialize all the needed variables and stuff and after doing so print to the user that the program is ready

**Comment by mayisa87** [comment]
You did oversee part (2), move definition of the guessedLettersList after the for loop. In general, always try to define the variables shortly before first usage, you can easily see where if you just click on the variable declaration and then check where you need it first time

![image](https://github.com/pothigai/HangManApp/assets/130921606/211a9e35-6b56-47a8-8918-e26f6c117053)

As here, you got a lot of code between declaration and first usage, which makes it harder to follow and read your code.
